# Generated by Django 6.0.3 on 2026-03-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='auth',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='auth',
            old_name='Username',
            new_name='username',
        ),
    ]
